steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/concise-rune-302709/recaptcha-demo:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/concise-rune-302709/recaptcha-demo:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'recaptcha-demo', '--image', 'gcr.io/concise-rune-302709/recaptcha-demo:$COMMIT_SHA', '--region', 'us-central1', '--update-secrets', 'GOOGLE_APPLICATION_CREDENTIALS=recaptcha-client-sa-key:latest']
images:
- gcr.io/concise-rune-302709/recaptcha-demo:$COMMIT_SHA